In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

width, height = 10, 10 #Set width and height of the grid
grid = np.random.randint(0,9,(width,height)) #Initialise grid of width x height with random integers from 0-9
start = (0,0) #Set start position as (0,0)

print(grid)

[[8 5 6 0 4 2 2 2 3 5]
 [7 0 1 0 4 5 7 0 1 2]
 [8 5 1 3 7 3 6 0 1 6]
 [6 3 7 3 6 2 2 0 7 6]
 [4 1 0 2 1 1 7 8 1 8]
 [1 0 5 0 0 0 0 6 0 2]
 [6 0 2 5 5 6 5 2 3 4]
 [3 3 1 8 6 5 1 3 2 1]
 [8 7 4 5 2 1 4 6 4 7]
 [1 5 4 6 5 1 3 0 8 7]]
